apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"monitoring.coreos.com/v1","kind":"ServiceMonitor","metadata":{"annotations":{},"labels":{"app":"sample-postgres","app.kubernetes.io/component":"postgres-exporter","managed":"postgres-operator"},"name":"sample-postgres-exporter","namespace":"alpha"},"spec":{"endpoints":[{"interval":"30s","path":"/metrics","port":"metrics"}],"selector":{"matchLabels":{"app":"sample-postgres","app.kubernetes.io/component":"postgres-exporter"}}}}
  creationTimestamp: "2026-06-14T15:10:19Z"
  generation: 1
  labels:
    app: sample-postgres
    app.kubernetes.io/component: postgres-exporter
    managed: postgres-operator
  name: sample-postgres-exporter
  namespace: alpha
  resourceVersion: "36410119"
  uid: 6af53789-7285-417c-8667-4b9b0e0802a9
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  selector:
    matchLabels:
      app: sample-postgres
      app.kubernetes.io/component: postgres-exporter
