apiVersion: database.iheb.local/v1
kind: PostgreSQLCluster
metadata:
  annotations:
    finalImageTest: "1781450734"
    finalRbacFixTest: "1781450935"
    finalRbacPatchTest: "1781451205"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"database.iheb.local/v1","kind":"PostgreSQLCluster","metadata":{"annotations":{},"labels":{"app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"postgres-operator"},"name":"sample-postgres","namespace":"alpha"},"spec":{"backup":{"archiveTimeout":60,"backupImage":"quay.io/iheb_mbarek/postgres-barman:latest","barmanHost":"192.168.180.54","barmanServerName":"sample-postgres","barmanUser":"barman","enabled":true,"exposeService":true,"nodePort":30433,"replicationAllowedCIDR":"192.168.180.54/32","schedule":"0 2 * * *","sshSecretName":"barman-ssh-key","streamingUser":"streaming_barman","suspendScheduledBackups":false},"cpuLimit":"500m","cpuRequest":"250m","database":"appdb","image":"quay.io/iheb_mbarek/postgres-barman:latest","memoryLimit":"512Mi","memoryRequest":"256Mi","pgbouncer":{"defaultPoolSize":20,"enabled":true,"image":"docker.io/edoburu/pgbouncer:latest","maxClientConn":100,"poolMode":"transaction","replicas":1},"postgresVersion":"16","restore":{"enabled":false},"storageClassName":"nfs-client","storageSize":"5Gi","user":"appuser"}}
    reconcileAt: "1781448954"
  creationTimestamp: "2026-05-26T13:30:19Z"
  generation: 30
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: postgres-operator
  name: sample-postgres
  namespace: alpha
  resourceVersion: "36523075"
  uid: 7b0a0db1-90d3-48c3-b485-5f558e2aa7b1
spec:
  backup:
    archiveTimeout: 60
    backupImage: quay.io/iheb_mbarek/postgres-barman:latest
    barmanHost: 192.168.180.54
    barmanServerName: sample-postgres
    barmanUser: barman
    enabled: true
    exposeService: true
    nodePort: 30433
    replicationAllowedCIDR: 192.168.180.54/32
    schedule: 0 2 * * *
    sshSecretName: barman-ssh-key
    streamingUser: streaming_barman
    suspendScheduledBackups: false
  cpuLimit: 500m
  cpuRequest: 250m
  database: appdb
  image: quay.io/iheb_mbarek/postgres-barman:latest
  memoryLimit: 512Mi
  memoryRequest: 256Mi
  pgbouncer:
    defaultPoolSize: 20
    enabled: true
    image: docker.io/edoburu/pgbouncer:latest
    maxClientConn: 100
    poolMode: transaction
    replicas: 1
  postgresVersion: "16"
  restore:
    backupId: 20260614T185602
    confirmation: RESTORE sample-postgres
    enabled: false
    preserveExistingData: true
    requestId: clean-pitr-proof-1781457246
    targetAction: promote
    targetTime: "2026-06-14T17:09:54.593Z"
  storageClassName: nfs-client
  storageSize: 5Gi
  user: appuser
status:
  backupCronJob: sample-postgres-barman-backup
  backupEnabled: true
  backupPhase: Scheduled
  backupSchedule: 0 2 * * *
  barmanNodePort: 30433
  barmanService: sample-postgres-barman
  lastBackupId: 20260614T185602
  lastBackupStatus: DONE
  lastBackupTime: "2026-06-14T14:56:24Z"
  lastRestoreTime: "2026-06-14T17:15:17Z"
  observedRestoreRequestId: clean-pitr-proof-1781457246
  pgbouncerEnabled: true
  pgbouncerPhase: Available
  pgbouncerService: sample-postgres-pgbouncer
  phase: Running
  postgresPod: sample-postgres-0
  ready: true
  restoreBackupId: 20260614T185602
  restoreMessage: restore is disabled
  restorePhase: Disabled
  restoreTargetTime: "2026-06-14T17:09:54Z"
