apiVersion: database.iheb.local/v1
kind: PostgreSQLBackup
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresqlbackup-sample
spec:
  # TODO(user): Add fields here
