apiVersion: database.iheb.local/v1
kind: PostgreSQLCluster
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample-postgres
spec:
  postgresVersion: "16"
  image: "quay.io/iheb_mbarek/postgres-barman:latest"
  database: "appdb"
  user: "appuser"
  storageSize: "5Gi"
  storageClassName: "nfs-client"

  cpuRequest: "250m"
  cpuLimit: "500m"
  memoryRequest: "256Mi"
  memoryLimit: "512Mi"
  
  backup:
    enabled: true
    barmanHost: "192.168.180.54"
    barmanUser: "barman"
    barmanServerName: "sample-postgres"
    sshSecretName: "barman-ssh-key"
    archiveTimeout: 60
    exposeService: true
    nodePort: 30433
    replicationAllowedCIDR: "192.168.180.54/32"
    streamingUser: "streaming_barman"
    schedule: "0 2 * * *"
    suspendScheduledBackups: false
    backupImage: quay.io/iheb_mbarek/postgres-barman:latest

  restore:
    enabled: false
