apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2026-05-26T13:46:06Z"
  labels:
    app: sample-postgres
    endpoints.kubernetes.io/managed-by: endpoint-controller
    managed: postgres-operator
    service.kubernetes.io/headless: ""
  name: sample-postgres
  namespace: alpha
  resourceVersion: "36673490"
  uid: c282b64b-d88d-44ee-8de1-a419b763ea89
subsets:
- addresses:
  - hostname: sample-postgres-0
    ip: 10.129.0.16
    nodeName: master01
    targetRef:
      kind: Pod
      name: sample-postgres-0
      namespace: alpha
      uid: 627ea119-8f12-4861-8690-192fd03ec89b
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
