apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-operator-controller-manager-metrics-monitor
  namespace: pg-guardian-olm
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/managed-by: olm
spec:
  namespaceSelector:
    matchNames:
      - pg-guardian-olm
  selector:
    matchLabels:
      control-plane: controller-manager
  endpoints:
    - port: https
      scheme: https
      path: /metrics
      interval: 30s
      tlsConfig:
        insecureSkipVerify: true
