apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator-metrics-ca.yaml
  - operator-metrics-scraper-serviceaccount.yaml
  - operator-metrics-scraper-token.yaml
  - operator-metrics-scraper-binding.yaml
  - operator-secure-servicemonitor.yaml
  - pg-guardian-operator-alerts.yaml
