apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-guardian-metrics-scraper
  namespace: postgres-operator-system
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/component: metrics-scraper
